GET http://localhost:3000/api/user
###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username":"bina89",
    "email":"bina89@examplee.com",
    "password":"1234567"
}
###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email":"bininahu12@gmail.com",
    "password":"12192123"
}
###

PUT http://localhost:3000/api/user/update/65f99b47fffd6cc7a848c514
Content-Type: application/json

{
    "username":"biniye2rt"
}
###

DELETE http://localhost:3000/api/user/delete/660a7cbf859588b82b6ef0e6
###

GET http://localhost:3000/api/post/getPosts
###

GET http://localhost:3000/api/user/getUsers?limit=1